version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fs_project
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql-db/script-db.sql:/docker-entrypoint-initdb.d/script-db.sql
    networks:
      - fs-net

  backend:
    build: ./fs-project-backend
    container_name: fs_backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/fs_project
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - fs-net

  frontend:
      build: ./fs-project-frontend
      container_name: fs_frontend
      ports:
        - "4200:80"
      depends_on:
        - backend
      networks:
        - fs-net

volumes:
  mysql_data:

networks:
  fs-net: